## lab 2

## Get our imports

In [1]:
import numpy as np
from sklearn import tree #see http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html


## Get our data: we'll use the iris data set for now

In [2]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data
y = data.target
print X.shape
print y.shape


(150, 4)
(150,)


In [ ]:
# print the first 5 rows
print(X[:5])

## Split into training and test sets

## The reason we do this is that sometimes our classifier will fit the data so well that it reflects the ideosyncracies of our sample, and not generalize well. This is called overfitting. To get a good idea of how the classifier would do on data it hasn't seen, we reserve some data that we will not use for training and test it out on that.

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [4]:
clf = tree.DecisionTreeClassifier(criterion="entropy") #see http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

## To see how we did, test on training set

In [5]:
clf.fit(X_train, y_train)
acc_train = clf.score(X_train, y_train)
acc_test = clf.score(X_test, y_test)

print("Accuracy on training data:", acc_train)
print("Accuracy on test data:", acc_test)

('Accuracy on training data:', 1.0)
('Accuracy on test data:', 0.97999999999999998)


Try out a different min samples split and see the difference

In [6]:
clf1 = tree.DecisionTreeClassifier(criterion="entropy", min_samples_split=2)
clf2 = tree.DecisionTreeClassifier(criterion="entropy", min_samples_split=50)

clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

acc_min_samples_split_2 = clf1.score(X_test, y_test)
acc_min_samples_split_50 = clf2.score(X_test, y_test)

print("Accuracy with min split = 2:", acc_min_samples_split_2)
print("Accuracy with min split = 50:", acc_min_samples_split_50)

('Accuracy with min split = 2:', 0.97999999999999998)
('Accuracy with min split = 50:', 0.97999999999999998)


In [7]:
tree.export_graphviz(clf, out_file='imgs/tree.dot')

! dot -Tpng imgs/tree.dot -o imgs/result.png


![](imgs/result.png)

In [8]:
my_data =  np.loadtxt('willwait_data.csv', dtype=str, delimiter=',')
print(my_data[:5])

#Need to convert everything to numerical values
my_data[my_data=='No'] = 0
my_data[my_data =='None'] = 0
my_data[my_data=='$'] = 0
my_data[my_data=='Mexican'] = 0
my_data[my_data=='10'] = 0

my_data[my_data=='Yes'] = 1
my_data[my_data=='Some'] = 1
my_data[my_data=='$$'] = 1
my_data[my_data=='Thai'] = 1
my_data[my_data=='30'] = 1

my_data[my_data=='Full'] = 2
my_data[my_data=='$$$'] = 2
my_data[my_data=='Burger'] = 2
my_data[my_data=='60'] = 2

my_data[my_data=='Italian'] = 3

my_data = np.delete(my_data, 0, 1) 
my_data = np.delete(my_data, 0, 0).astype('float64') 

print(my_data[:5])

[[ 0.  1.  1.  0.  1.  1.  0.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  1.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  1.  0.  1.  1.  0.]
 [ 0.  1.  1.  0.  1.  0.  0.  0.  0.  3.  0.]
 [ 0.  1.  1.  0.  1.  1.  0.  0.  0.  1.  0.]]


In [9]:
restaurant_y = my_data[:, 0]
print(restaurant_y)

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.
  1.  1.  1.]


In [10]:
restaurant_X = my_data[:, 1:]
print(restaurant_X[:5])

[[ 1.  1.  0.  1.  1.  0.  0.  1.  0.  0.]
 [ 1.  1.  0.  1.  0.  1.  0.  1.  0.  0.]
 [ 1.  1.  0.  1.  0.  1.  0.  1.  1.  0.]
 [ 1.  1.  0.  1.  0.  0.  0.  0.  3.  0.]
 [ 1.  1.  0.  1.  1.  0.  0.  0.  1.  0.]]


In [11]:
clfr = tree.DecisionTreeClassifier(criterion="entropy")

In [12]:
Xr_train, Xr_test, yr_train, yr_test = train_test_split(restaurant_X, restaurant_y, test_size=0.33)

In [13]:
clfr.fit(Xr_train, yr_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [14]:
accr_train = clfr.score(Xr_train, yr_train)
accr_test = clfr.score(Xr_test, yr_test)
print("Accuracy on training data:", accr_train)
print("Accuracy on test data:", accr_test)

('Accuracy on training data:', 1.0)
('Accuracy on test data:', 0.76923076923076927)


In [15]:
tree.export_graphviz(clfr, out_file='imgs/treer.dot')

! dot -Tpng imgs/treer.dot -o imgs/resultr.png

![](imgs/resultr.png)