## 1. Import the numpy package with the alias np

In [22]:
import numpy as np

## 2. Create a vector of zeros of size 10 but the fifth value which is 1

In [23]:
a= np.zeros(10, dtype=int)
a[4] = 1
print(a)


[0 0 0 0 1 0 0 0 0 0]


## 3. Create a 3 X 3 array of any values. Add a column of ones to the end

In [24]:
a = np.arange(1,10).reshape((3,3))
print(a)
b = np.array([[1,1,1]])
a= np.concatenate((a,b.T), axis = 1)
print(" Add a coloumn of one to the end\n" ,a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 Add a coloumn of one to the end
 [[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]


## 4. Create a vector with values ranging from 10 to 49

In [25]:
a = np.arange(10, 50)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 5. Reverse the above vector (first element becomes last)

In [26]:
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## 6. Create a 4x4 matrix with values ranging from 0 to 15

In [27]:
a = np.arange(16).reshape((4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 7. Create a 3x3x3 array with random values

In [28]:
a = np.floor(9 * np.random.random((3,3,3))).astype(int)
print(a)

[[[6 2 0]
  [0 7 4]
  [2 5 0]]

 [[2 3 5]
  [6 1 0]
  [7 8 2]]

 [[3 8 8]
  [0 6 8]
  [1 3 7]]]


## 8. Create a 10x10 array with random values and find the minimum and maximum values

In [29]:
a = np.floor(50 * np.random.random((10,10))).astype(int)
print(a)
print("Min:", a.min())
print("Max:", a.max())

[[41 13  9 31 19 28 28 29 36 26]
 [20 43  4 40 20  7 23 23 40 40]
 [31 29  9 10  5 16 36  5 28  0]
 [25 28 39  5 35 29 34 48  4 46]
 [15 28 41  2 32 32  5 15  3 30]
 [41 46 37  2 46 17 28 38 33 38]
 [ 0 33 23 25 15 34 48 33 35 47]
 [15 30 49 31 10 22 47 37 31 34]
 [ 5 37 23 30  6 13 28  8 40 27]
 [ 7 15  4 37 43 38 36  8 32  3]]
Min: 0
Max: 49


## 9. Create a random vector of size 30 and find the mean value

In [30]:
a = np.floor(50 * np.random.random((30,))).astype(int)
print(a)
print("Mean:", np.mean(a))

[ 2  5 16  7 21 29 29  1  3 19  6  0  7 44 14 31 37 35 16 49 42 31 29 47 22
  3 41 14 19  6]
Mean: 20.8333333333


## 10. What does NaN mean? Submit in a comment

NaN = not a number


## 11. Write a function that takes 1D array and negates all elements which are between 3 and 8, in place. Demo it with an array of your choosing

In [31]:
a[(3 <= a) & (a <= 8)] *= -1
print(a)

[ 2 -5 16 -7 21 29 29  1 -3 19 -6  0 -7 44 14 31 37 35 16 49 42 31 29 47 22
 -3 41 14 19 -6]
